export const FETCH_PERIPHERALS = 'FETCH_PERIPHERALS'
export const FETCH_PERIPHERALS_LOADING = 'FETCH_PERIPHERALS_LOADING'
export const FETCH_PERIPHERALS_RESET = 'FETCH_PERIPHERALS_RESET'
export const FETCH_PERIPHERALS_ID = 'FETCH_PERIPHERALS_ID'
export const FETCH_DETAIL_PERIPHERAL = 'FETCH_DETAIL_PERIPHERAL'

export const FETCH_RESTAURANT = 'FETCH_RESTAURANT'

export const FETCH_TABLE_NUM = 'FETCH_TABLE_NUM'
export const FETCH_CUST_REST_ID = 'FETCH_CUST_REST_ID'